M48
; DRILL file {KiCad 7.0.7} date Tue Sep 17 12:02:04 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-17T12:02:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X5.4256Y-3.1144
X5.6531Y-3.1144
T2
X4.8661Y-2.9915
X4.8661Y-4.7249
X6.2037Y-2.9915
X6.2037Y-4.7249
T0
M30
